codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-020-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-020-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-020-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-020-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-022-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-022-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-022-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-022-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-022-3 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-022-3
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-078-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-078-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-078-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-078-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-078-3 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-078-3
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-079-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-079-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-079-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-079-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-079-3 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-079-3
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-089-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-089-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-089-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-089-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-089-3 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-089-3
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-089-4 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-089-4
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-094-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-094-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-094-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-094-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-117-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-117-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-208-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-208-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-208-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-208-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-209-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-209-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-287-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-287-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-287-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-287-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-295-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-295-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-295-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-295-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-326-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-326-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-326-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-326-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-327-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-327-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-327-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-327-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-327-3 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-327-3
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-327-4 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-327-4
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-338-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-338-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-347-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-347-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-348-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-348-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-348-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-348-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-400-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-400-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-502-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-502-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-601-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-601-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-601-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-601-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-611-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-611-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-611-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-611-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-614-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-614-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-614-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-614-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-643-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-643-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-643-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-643-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-730-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-730-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-730-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-730-2
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-798-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-798-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-918-1 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-918-1
codeql database create /home/huhu/work/CodeTransSecEval/data/databases/gpt4/CWE-918-2 --overwrite --language=java --source-root=/home/huhu/work/CodeTransSecEval/data/predictions/gpt4/CWE-918-2